name: Dispatch

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: write-all

jobs:
  # infra:
  #   name: Deploy Terraform
  #   uses: ./.github/workflows/infra.yaml
  #   secrets: inherit
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo "hello"
 
